### PR TITLE
[PM-10900] Add coding keys to MasterPasswordPolicyResponseModel

### PR DESCRIPTION
**Pull request by andrebispo5**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-10900

## 📔 Objective

The identity response model for the master password policy wasn't deserialising properly, adding coding keys fixed the issue.

## 📸 Screenshots

Without coding keys:
image

With coding keys:
image

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Comment by fedemkr** [comment]
I see this being discussed here https://github.com/bitwarden/ios/pull/1065#discussion_r1852704070.
X-posting here so we have the discussion on this open PR:

@andrebispo5 I believe this is because `IdentityTokenErrorModel` doesn't conform to `JSONResponse`, thus it doesn't use the `pascalOrSnakeCaseDecoder`.
I think we could just change: 
`try? JSONDecoder().decode` 
for 
`try? JSONDecoder.pascalOrSnakeCaseDecoder.decode`
in here and that should fix the issue without the `CodingKeys`
https://github.com/bitwarden/ios/blob/1f97eabc83c4c8d61109036bf34af574d32f3c4e/BitwardenShared/Core/Auth/Services/API/Auth/Requests/IdentityTokenRequest.swift#L80-L84

What do you think @matt-livefront ?

**Comment by matt-livefront** [comment]
> I see this being discussed here [#1065 (comment)](https://github.com/bitwarden/ios/pull/1065#discussion_r1852704070). X-posting here so we have the discussion on this open PR:
> 
> @andrebispo5 I believe this is because `IdentityTokenErrorModel` doesn't conform to `JSONResponse`, thus it doesn't use the `pascalOrSnakeCaseDecoder`. I think we could just change: `try? JSONDecoder().decode` for `try? JSONDecoder.pascalOrSnakeCaseDecoder.decode` in here and that should fix the issue without the `CodingKeys`
> 
> https://github.com/bitwarden/ios/blob/1f97eabc83c4c8d61109036bf34af574d32f3c4e/BitwardenShared/Core/Auth/Services/API/Auth/Requests/IdentityTokenRequest.swift#L80-L84
> 
> What do you think @matt-livefront ?

@fedemkr I like that! Less to maintain and makes it more flexible.

**Comment by andrebispo5** [comment]
> > I see this being discussed here [#1065 (comment)](https://github.com/bitwarden/ios/pull/1065#discussion_r1852704070). X-posting here so we have the discussion on this open PR:
> > @andrebispo5 I believe this is because `IdentityTokenErrorModel` doesn't conform to `JSONResponse`, thus it doesn't use the `pascalOrSnakeCaseDecoder`. I think we could just change: `try? JSONDecoder().decode` for `try? JSONDecoder.pascalOrSnakeCaseDecoder.decode` in here and that should fix the issue without the `CodingKeys`
> > https://github.com/bitwarden/ios/blob/1f97eabc83c4c8d61109036bf34af574d32f3c4e/BitwardenShared/Core/Auth/Services/API/Auth/Requests/IdentityTokenRequest.swift#L80-L84
> > 
> > What do you think @matt-livefront ?
> 
> @fedemkr I like that! Less to maintain and makes it more flexible.

Oh nice, ye that is way cleaner. On it!

**Review by fedemkr — APPROVED** [review]
✅  The lowercase situation is not good but I think it's a good tradeoff against having all the other Coding keys, so approving 😄 
♻️  Additionally, I believe we might have a non-optimal solution for `snake_case` handling given that `HCaptcha_SiteKey` should be transformed into `hCaptchaSiteKey` instead of `hcaptchaSitekey`; but well it's out of the scope of this PR and fixing it could break other places so we can leave it as is for now.

**Comment by andrebispo5** [comment]
@fedemkr @matt-livefront Having to change all the coding keys from 

> ✅ The lowercase situation is not good but I think it's a good tradeoff against having all the other Coding keys, so approving 😄 ♻️ Additionally, I believe we might have a non-optimal solution for `snake_case` handling given that `HCaptcha_SiteKey` should be transformed into `hCaptchaSiteKey` instead of `hcaptchaSitekey`; but well it's out of the scope of this PR and fixing it could break other places so we can leave it as is for now.

Agreed, but given the fact that we also removed some coding keys, I think the trade off was nice. I was also not expecting the snakecase to behave that way (found it the hard way). We can create a tech dept item to look into refactor it.

**Pull request merged**
