### PR TITLE
[PM-9907] Change language codes for Chinese and Brazilian Portuguese

### PR DESCRIPTION
**Pull request by Hinton**
## 🎟️ Tracking

https://bitwarden.atlassian.net/browse/PM-12977

## 📔 Objective

iOS prefers to use the `zh-Hans` and `zh-Hant` language codes for traditional / simplified Chinese rather than `zh-CN` and `zh-TW` that we previously used. This seems to resolve the issues around the language not working however it also changes how we represent it in the language picker.

We should confirm this language codes are what we desire to use, and how they behave with the system language options.

## 📸 Screenshots

Before:
image

After:
image

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by KatherineInCode — APPROVED** [review]
Approving because these look good to me, especially if they fix the issue, but I can't comment on the names, unfortunately.

**Comment by KatherineInCode** [comment]
📝 You will need to also update the snapshot tests for this. Particularly, `BitwardenShared/UI/Platform/Settings/Settings/Appearance/SelectLanguage/__Snapshots__/SelectLanguageViewTests/test_snapshot_default_large.1.png` will need to be regenerated to capture the new names. If you delete that file then run the tests it should generate the new snapshot for you.

**Review by matt-livefront — APPROVED** [review]
This changes make sense, as those codes should match what we have in the Info.plist and Localized string files.

Bitwarden/Application/Support/Info.plist:
```
<string>pt-PT</string>
<string>pt-BR</string>
<string>zh-Hans</string>
<string>zh-Hant</string>
```

BitwardenShared/UI/Platform/Application/Support/Localizations:
```
pt-BR.lproj
pt-PT.lproj
zh-Hans.lproj
zh-Hant.lproj
```

One thing I noticed though, if I set my system language (as opposed to the app's override) to simplified Chinese, I'm still only seeing English.

We currently use `Locale.current.languageCode` to get the user's system language code, but maybe we should instead be using the bundle's `preferredLocalizations` array.

```
(lldb) po Locale.current.languageCode
▿ Optional<String>
  - some : "zh"
(lldb) po Bundle.main.preferredLocalizations
▿ 1 element
  - 0 : "zh-Hans"
 ```

**Comment by Hinton** [comment]
Seems I'm using Xcode 16 which isn't supported by our codebase yet 😓.

**Review by matt-livefront — APPROVED** [review]

**Comment by jiaobaba1027** [comment]
When can it be repaired?

**Pull request merged**
