### PR TITLE
[PM-11322] Adding more comment for organizationService param at PolicyService.swift

### PR DESCRIPTION
**Pull request by lamtrinhdev**
## 📔 Objective

Adding more comment for `organizationService` param at `PolicyService.swift`

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed

### CODE REVIEW

**Review by KatherineInCode — APPROVED** [review]
👍🏻 Great catch! Thank you for your contribution!

**Comment by lamtrinhdev** [comment]
Dear @KatherineInCode ,

I does not have permission to merge. Could you please help me to merge it?

Thanks,
Lam

**Comment by lamtrinhdev** [comment]
Dear @KatherineInCode ,

Thank you for your review. I does not have permission to merge. Could you please help me to merge it?

Thanks,
Lam

**Comment by lamtrinhdev** [comment]
Dear @KatherineInCode ,

It is so cool. Thank you for your merging.

Thanks,
Lam

**Pull request merged**
